env: flex
runtime: custom #not nodejs as we are running container in docker, setup everything in dockerfile
service: client
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10